/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-5f25e5e2",
        "v-6d73b402"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-11b5251c",
        "v-f0ad93cc"
      ]
    }
  },
  "categories": {
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-5f25e5e2",
        "v-6d73b402"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-11b5251c",
        "v-f0ad93cc"
      ]
    }
  },
  "timeline": {}
}