/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-72ecb542",
        "v-649ee722"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-02a0af95",
        "v-7894c093"
      ]
    }
  },
  "categories": {
    "CSS": {
      "key": "CSS",
      "scope": "categories",
      "path": "/categories/CSS/",
      "pageKeys": [
        "v-72ecb542",
        "v-649ee722"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-02a0af95",
        "v-7894c093"
      ]
    }
  },
  "timeline": {}
}